"""Generate filters/gen_symbols.mbt (the SymbolFilter tables) from Python.

Usage: python3 scripts/export_filters.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, '.repos', 'pygments'))

from pygments.filters import SymbolFilter  # noqa: E402

OUT = os.path.join(ROOT, 'filters', 'gen_symbols.mbt')


def mbt_str(s):
    out = ['"']
    for ch in s:
        c = ord(ch)
        if ch in '"\\':
            out.append('\\' + ch)
        elif c < 0x20 or c == 0x7f:
            out.append('\\u{%x}' % c)
        else:
            out.append(ch)
    out.append('"')
    return ''.join(out)


def main():
    parts = ['// Generated by scripts/export_filters.py from the pinned Pygments '
             'checkout. DO NOT EDIT.\n']
    for name, table in [('latex', SymbolFilter.latex_symbols),
                        ('isabelle', SymbolFilter.isabelle_symbols)]:
        parts.append(f'\n///|\n/// `SymbolFilter.{name}_symbols`.\n'
                     f'let {name}_symbols : Map[String, String] = Map([\n')
        for k, v in table.items():
            parts.append(f'  ({mbt_str(k)}, {mbt_str(v)}),\n')
        parts.append('])\n')
    with open(OUT, 'w') as f:
        f.write(''.join(parts))


main()
