"""Generate styles/gen_*.mbt from the builtin Pygments styles.

For every style class listed in `pygments.styles._mapping.STYLES` we export
the class attributes (name, colors, ...) and the raw `styles` dictionary as
seen *after* `StyleMeta` ran (so it already contains the empty entries the
metaclass adds for every standard token type, in Python's order).
`Style::new` in MoonBit replays the metaclass on that data; the processed
per-token dicts are checked against Python by `cmd/formatter_oracle`
(`.oracle/styles.jsonl`, written by `scripts/formatter_oracle.py`).

Usage: python3 scripts/export_styles.py
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, '.repos', 'pygments'))

from pygments.styles._mapping import STYLES  # noqa: E402
from pygments.styles import get_style_by_name  # noqa: E402

OUT = os.path.join(ROOT, 'styles')


def mbt_str(s):
    out = ['"']
    for c in s:
        if c == '"':
            out.append('\\"')
        elif c == '\\':
            out.append('\\\\')
        elif c == '\n':
            out.append('\\n')
        elif c == '\t':
            out.append('\\t')
        elif ord(c) < 0x20 or ord(c) == 0x7f:
            out.append('\\u{%x}' % ord(c))
        else:
            out.append(c)
    out.append('"')
    return ''.join(out)


def snake(name):
    s = re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', name)
    return s.replace('__', '_').lower()


def opt_str(v):
    return 'None' if v is None else f'Some({mbt_str(v)})'


def emit_style(cls_name, mod, style_name):
    st = get_style_by_name(style_name)
    assert st.__name__ == cls_name, (st.__name__, cls_name)
    fn = snake(cls_name)
    lines = []
    lines.append('///|')
    lines.append(f'/// Python\'s `{mod}.{cls_name}` (style `{style_name}`).')
    lines.append(f'pub fn {fn}() -> Style {{')
    lines.append(f'  builtin({mbt_str(style_name)}, fn() {{')
    lines.append('    make(')
    lines.append(f'      {mbt_str(st.name)},')
    lines.append('      [' + ', '.join(mbt_str(a) for a in st.aliases) + '],')
    lines.append(f'      {opt_str(st.background_color)},')
    lines.append(f'      {opt_str(st.highlight_color)},')
    lines.append(f'      {mbt_str(st.line_number_color)},')
    lines.append(f'      {mbt_str(st.line_number_background_color)},')
    lines.append(f'      {mbt_str(st.line_number_special_color)},')
    lines.append(f'      {mbt_str(st.line_number_special_background_color)},')
    lines.append(f'      {"true" if st.web_style_gallery_exclude else "false"},')
    lines.append('      [')
    for tok, val in st.styles.items():
        lines.append(f'        ({mbt_str(str(tok))}, {mbt_str(val)}),')
    lines.append('      ],')
    lines.append('    )')
    lines.append('  })')
    lines.append('}')
    return fn, '\n'.join(lines) + '\n'


def main():
    by_module = {}
    registry = []
    for cls_name, (mod, style_name, _aliases) in STYLES.items():
        fn, code = emit_style(cls_name, mod, style_name)
        by_module.setdefault(mod.split('.')[-1], []).append(code)
        registry.append((style_name, fn))
    for old in os.listdir(OUT):
        if old.startswith('gen_') and old.endswith('.mbt'):
            os.remove(os.path.join(OUT, old))
    header = ('// Generated by scripts/export_styles.py from the pinned Pygments '
              'checkout. DO NOT EDIT.\n\n')
    for module, codes in sorted(by_module.items()):
        with open(os.path.join(OUT, f'gen_{module}.mbt'), 'w') as f:
            f.write(header + '\n'.join(codes))
    with open(os.path.join(OUT, 'gen_registry.mbt'), 'w') as f:
        f.write(header)
        f.write('///|\n/// The builtin styles in `pygments.styles.STYLES` order: '
                '(name, constructor).\nlet builtin_styles : Array[(String, () -> Style)] = [\n')
        for name, fn in registry:
            f.write(f'  ({mbt_str(name)}, {fn}),\n')
        f.write(']\n')
    print(len(registry), 'styles')


main()
