"""Export docstrings used by `pygmentize -L` / `-H` into
cmd/pygmentize/gen_docs.mbt (formatters, filters, styles)."""
import sys, os, textwrap
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, '.repos', 'pygments'))
sys.path.insert(0, HERE)
from export_lexers import mbt_str  # noqa: E402  (runs the lexer export too)
from pygments.formatters import get_all_formatters
from pygments.filters import get_all_filters, find_filter_class
from pygments.styles import get_all_styles, get_style_by_name


def table(name, pairs, doc):
    out = [f'///|\n/// {doc}\nlet {name} : Map[String, String] = Map::from_array([']
    for k, v in pairs:
        out.append(f'  ({mbt_str(k)}, {mbt_str(v)}),')
    out.append('])\n')
    return '\n'.join(out)


parts = ['// Generated by scripts/export_cli_docs.py. DO NOT EDIT.\n']
parts.append(table('formatter_docs', [(c.name, textwrap.dedent(c.__doc__ or '')) for c in get_all_formatters()],
                   'Formatter docstrings by display name.'))
parts.append(table('filter_docs', [(n, textwrap.dedent(find_filter_class(n).__doc__ or '')) for n in get_all_filters()],
                   'Filter docstrings by name.'))
parts.append(table('style_docs', [(n, get_style_by_name(n).__doc__ or '') for n in get_all_styles()],
                   'Style docstrings by name.'))
open(os.path.join(ROOT, 'cmd', 'pygmentize', 'gen_docs.mbt'), 'w').write('\n'.join(parts))
