"""Generate regex/unicode_tables.mbt from the running CPython's `re` module.

The tables pin the semantics of `\\w`, `\\d`, `\\s` (Unicode mode) and the
case-insensitive equivalences used by `re.IGNORECASE`, so the MoonBit engine
agrees with the Python oracle.
"""
import re, sys, _sre
from re import _casefix

MAXCP = 0x110000


def ranges_of(pred):
    out = []
    start = None
    for c in range(MAXCP):
        if pred(c):
            if start is None:
                start = c
        elif start is not None:
            out.append((start, c - 1))
            start = None
    if start is not None:
        out.append((start, MAXCP - 1))
    return out


def by_regex(pat):
    r = re.compile(pat)
    return lambda c: (0xD800 > c or c > 0xDFFF) and r.match(chr(c)) is not None


word = ranges_of(by_regex(r'\w'))
digit = ranges_of(by_regex(r'\d'))
space = ranges_of(by_regex(r'\s'))

lower = [(c, _sre.unicode_tolower(c)) for c in range(MAXCP)
         if _sre.unicode_tolower(c) != c]

fixes = _casefix._EXTRA_CASES
groups = {}
for c in range(MAXCP):
    groups.setdefault(_sre.unicode_tolower(c), []).append(c)
equiv = []
for c in range(MAXCP):
    lo = _sre.unicode_tolower(c)
    keys = [lo] + list(fixes.get(lo, ()))
    members = sorted({x for k in keys for x in groups.get(k, [])} | {c})
    if members != [c]:
        equiv.append((c, members))


def flat(pairs):
    return ", ".join(f"{a}, {b}" for a, b in pairs)


def emit_array(name, values, doc):
    lines = [f"///|\n/// {doc}\nlet {name} : FixedArray[Int] = ["]
    row = []
    for v in values:
        row.append(str(v))
        if len(row) == 16:
            lines.append("  " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("  " + ", ".join(row) + ",")
    lines.append("]\n")
    return "\n".join(lines)


out = [f"// Generated by scripts/gen_unicode_tables.py from Python {sys.version_info[0]}.{sys.version_info[1]}. DO NOT EDIT.\n"]
out.append(emit_array("word_ranges", [x for r in word for x in r],
                      "Inclusive code point ranges matched by Python's Unicode `\\w`."))
out.append(emit_array("digit_ranges", [x for r in digit for x in r],
                      "Inclusive code point ranges matched by Python's Unicode `\\d`."))
out.append(emit_array("space_ranges", [x for r in space for x in r],
                      "Inclusive code point ranges matched by Python's Unicode `\\s`."))
out.append(emit_array("lower_map", [x for p in lower for x in p],
                      "Pairs `(cp, lower)` of `_sre.unicode_tolower` where it differs from `cp`."))
keys, offs, mems = [], [], []
for c, ms in equiv:
    keys.append(c)
    offs.append(len(mems))
    mems.extend(ms)
offs.append(len(mems))
out.append(emit_array("case_equiv_keys", keys,
                      "Code points whose IGNORECASE equivalence class is non-trivial (sorted)."))
out.append(emit_array("case_equiv_offsets", offs,
                      "Offsets into `case_equiv_members`, parallel to `case_equiv_keys` (+1 sentinel)."))
out.append(emit_array("case_equiv_members", mems,
                      "Concatenated equivalence classes (each sorted, including the key)."))
open(sys.argv[1], "w").write("\n".join(out))
print(len(word), len(digit), len(space), len(lower), len(equiv))
