"""Generate pystr/gen_tables.mbt from the running CPython (the oracle).

The tables pin the semantics of `str.isprintable` (used by `repr`), and of
`str.lower`/`str.upper`/`str.capitalize` (full case mappings plus the
properties needed for the final-sigma rule), so the MoonBit helpers agree
with Python byte for byte.

Usage: python3 scripts/gen_pystr_tables.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, 'pystr', 'gen_tables.mbt')
MAXCP = 0x110000


def is_surrogate(c):
    return 0xD800 <= c <= 0xDFFF


def ranges_of(pred):
    out = []
    start = None
    for c in range(MAXCP):
        if pred(c):
            if start is None:
                start = c
        elif start is not None:
            out.append((start, c - 1))
            start = None
    if start is not None:
        out.append((start, MAXCP - 1))
    return out


def cased(c):
    ch = chr(c)
    return ch.islower() or ch.isupper() or ch.istitle()


def case_ignorable(c):
    if is_surrogate(c) or c == 0x3A3:
        return False
    ch = chr(c)
    if cased(c):
        # (c + SIGMA) lowers to a final sigma iff c is cased and not ignorable.
        return (ch + 'Σ').lower()[-1] != 'ς'
    # ('A' + c + SIGMA) lowers to a final sigma iff c is ignorable or cased.
    return ('A' + ch + 'Σ').lower()[-1] == 'ς'


def mbt_str(s):
    return '"' + ''.join('\\u{%x}' % ord(ch) if (ord(ch) < 0x20 or ord(ch) > 0x7e or ch in '"\\') else ch for ch in s) + '"'


def emit_ranges(name, ranges, doc):
    body = []
    row = []
    for a, b in ranges:
        row.append(f'{a}, {b}')
        if len(row) == 8:
            body.append('  ' + ', '.join(row) + ',')
            row = []
    if row:
        body.append('  ' + ', '.join(row) + ',')
    return f'///|\n/// {doc}\nlet {name} : FixedArray[Int] = [\n' + '\n'.join(body) + '\n]\n'


def main():
    nonprint = ranges_of(lambda c: is_surrogate(c) or not chr(c).isprintable())
    cased_r = ranges_of(lambda c: not is_surrogate(c) and cased(c))
    ignorable_r = ranges_of(case_ignorable)
    case_rows = []
    for c in range(MAXCP):
        if is_surrogate(c):
            continue
        ch = chr(c)
        lo, up, ti = ch.lower(), ch.upper(), ch.title()
        if c == 0x3A3:
            lo = 'σ'  # the final-sigma rule is applied separately
        if (lo, up, ti) != (ch, ch, ch):
            case_rows.append((c, lo, up, ti))
    out = ['// Generated by scripts/gen_pystr_tables.py from CPython '
           f'{sys.version_info[0]}.{sys.version_info[1]}. DO NOT EDIT.\n']
    out.append(emit_ranges('nonprintable_ranges', nonprint,
                           'Inclusive code point ranges where `str.isprintable` is false.'))
    out.append(emit_ranges('cased_ranges', cased_r,
                           'Inclusive ranges of cased characters (final-sigma rule).'))
    out.append(emit_ranges('case_ignorable_ranges', ignorable_r,
                           'Inclusive ranges of case-ignorable characters (final-sigma rule).'))
    out.append('///|\n/// Full case mappings `(code point, lower, upper, title)` for every\n'
               '/// character where one of them differs from the character itself.\n'
               'let case_table : Array[(Int, String, String, String)] = [\n')
    for c, lo, up, ti in case_rows:
        out.append(f'  ({c}, {mbt_str(lo)}, {mbt_str(up)}, {mbt_str(ti)}),\n')
    out.append(']\n')
    with open(OUT, 'w') as f:
        f.write('\n'.join(out))
    print(len(nonprint), len(cased_r), len(ignorable_r), len(case_rows))


main()
